version: "3.7"

volumes:
  grafana-storage:
  octoprint:

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    command: mosquitto -c /mosquittoconf/mosquitto.conf
    ports:
      - 1883:1883
    volumes:
      - ./config/mosquitto:/mosquittoconf
    restart: unless-stopped
  grafana:
    image: grafana/grafana-oss
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - 3005:3000
    restart: unless-stopped
    environment:
      GF_PANELS_DISABLE_SANITIZE_HTML: "true"
      GF_SECURITY_ALLOW_EMBEDDING: "true"
  homeassistant:
    image: homeassistant/home-assistant:latest
    network_mode: host
    volumes:
      - ${HOME_DIR}/home-assistant:/config
    restart: unless-stopped
    environment:
      TZ: "Europe/London"
    depends_on:
      - mosquitto
  octoprint:
    image: octoprint/octoprint
    restart: unless-stopped
    ports:
      - 3006:80
    privileged: true
    environment:
      ENABLE_MJPG_STREAMER: "true"
      CAMERA_DEV: "${OCTO_CAM_PATH}"
    volumes:
      - octoprint:/octoprint
      - /dev:/dev
  rhasspy:
    image: "rhasspy/rhasspy"
    container_name: rhasspy
    restart: unless-stopped
    volumes:
      - "${HOME_DIR}/.config/rhasspy/profiles:/profiles"
      - "/etc/localtime:/etc/localtime:ro"
      - "${HOME_DIR}/.config/pulse/cookie:/root/.config/pulse/cookie"
      - "${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native"
    environment:
      PULSE_SERVER: "unix:${XDG_RUNTIME_DIR}/pulse/native"
    ports:
      - "12101:12101"
      - "12183:12183" # internal mqtt broker
    devices:
      - "/dev/snd:/dev/snd"
    command: --user-profiles /profiles --profile en
  larynx:
    image: "rhasspy/larynx"
    restart: unless-stopped
    tty: true
    ports:
      - "5002:5002"
    environment:
      HOME: "${HOME_DIR}"
    volumes:
      - "${HOME_DIR}:${HOME_DIR}"
      - "/usr/share/ca-certificates:/usr/share/ca-certificates"
      - "/etc/ssl/certs:/etc/ssl/certs"
  minecraftserver:
    image: "itzg/minecraft-bedrock-server"
    restart: unless-stopped
    ports:
      - "19132:19132/udp"
    environment:
      EULA: "TRUE"
      GAMEMODE: survival
      DIFFICULTY: easy
    volumes:
      - ${HOME_DIR}/minecraft-server:/data