version: "3.7"

volumes:
  grafana-storage:
  octoprint:
  node-red-data:

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    command: mosquitto -c /mosquittoconf/mosquitto.conf
    ports:
      - 1883:1883
    volumes:
      - ./config/mosquitto:/mosquittoconf
    restart: unless-stopped
  grafana:
    image: grafana/grafana-oss
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - 3005:3000
    restart: unless-stopped
    environment:
      GF_PANELS_DISABLE_SANITIZE_HTML: "true"
  homeassistant:
    image: homeassistant/home-assistant:latest
    network_mode: host
    volumes:
      - ${HOME_DIR}/home-assistant:/config
    restart: unless-stopped
    environment:
      TZ: "Europe/London"
    depends_on:
      - mosquitto
  octoprint:
    image: octoprint/octoprint
    restart: unless-stopped
    ports:
      - 3006:80
    devices:
      - ${PRINTER_DEVICE}:/dev/ttyACM0
    volumes:
      - octoprint:/octoprint
  node-red:
    image: nodered/node-red:latest
    environment:
      TZ: "Europe/London"
    ports:
      - 1880:1880
    network_mode: host
    volumes:
      - node-red-data:/data
      - /home/greg:/home/greg