#!/bin/bash
# octoprint only starts if printer serial device exists, as it gets mounted.
mosquitto_pub -h depth -t "cmnd/tasmota_sw_ender3pro/Power1" -m "ON"
sleep 1
cd ~/depth-srv
git pull
sudo docker-compose down
sudo docker-compose up --build -d
sleep 1
mosquitto_pub -h depth -t "cmnd/tasmota_sw_ender3pro/Power1" -m "OFF"
